CREATE TABLE "nhl_engine_state" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"game_state" text DEFAULT 'quiet' NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nhl_goalie_advanced_stats" (
	"id" text PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"season_id" integer NOT NULL,
	"game_type_id" integer NOT NULL,
	"games_played" integer NOT NULL,
	"team_abbrevs" text,
	"quality_start" integer,
	"quality_starts_pct" real,
	"complete_games" integer,
	"complete_game_pct" real,
	"incomplete_games" integer,
	"goals_for" integer,
	"goals_for_average" real,
	"goals_against" integer,
	"goals_against_average" real,
	"regulation_wins" integer,
	"regulation_losses" integer,
	"shots_against_per_60" real,
	"save_pct" real,
	"time_on_ice" real,
	"ev_saves" integer,
	"ev_shots_against" integer,
	"ev_save_pct" real,
	"ev_goals_against" integer,
	"pp_saves" integer,
	"pp_shots_against" integer,
	"pp_save_pct" real,
	"pp_goals_against" integer,
	"sh_saves" integer,
	"sh_shots_against" integer,
	"sh_save_pct" real,
	"sh_goals_against" integer,
	"total_saves" integer,
	"total_shots_against" integer,
	"total_save_pct" real,
	"total_goals_against" integer,
	"wins" integer,
	"losses" integer,
	"ot_losses" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nhl_skater_advanced_stats" (
	"id" text PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"season_id" integer NOT NULL,
	"game_type_id" integer NOT NULL,
	"games_played" integer NOT NULL,
	"position_code" text,
	"team_abbrevs" text,
	"hits" integer,
	"hits_per_60" real,
	"blocked_shots" integer,
	"blocked_shots_per_60" real,
	"missed_shots" integer,
	"giveaways" integer,
	"giveaways_per_60" real,
	"takeaways" integer,
	"takeaways_per_60" real,
	"empty_net_goals" integer,
	"empty_net_assists" integer,
	"empty_net_points" integer,
	"first_goals" integer,
	"ot_goals" integer,
	"shot_attempts_blocked" integer,
	"total_shot_attempts" integer,
	"time_on_ice_per_game" real,
	"sat_percentage" real,
	"sat_percentage_ahead" real,
	"sat_percentage_behind" real,
	"sat_percentage_tied" real,
	"sat_percentage_close" real,
	"sat_relative" real,
	"usat_percentage" real,
	"usat_percentage_ahead" real,
	"usat_percentage_behind" real,
	"usat_percentage_tied" real,
	"usat_percentage_close" real,
	"usat_relative" real,
	"shooting_pct_5v5" real,
	"skater_save_pct_5v5" real,
	"skater_shooting_plus_save_pct_5v5" real,
	"zone_start_pct_5v5" real,
	"time_on_ice_per_game_5v5" real,
	"goals_5v5" integer,
	"goals_per_60_5v5" real,
	"assists_5v5" integer,
	"assists_per_60_5v5" real,
	"points_5v5" integer,
	"points_per_60_5v5" real,
	"primary_assists_5v5" integer,
	"primary_assists_per_60_5v5" real,
	"secondary_assists_5v5" integer,
	"secondary_assists_per_60_5v5" real,
	"offensive_zone_start_pct_5v5" real,
	"on_ice_shooting_pct_5v5" real,
	"net_minor_penalties_per_60" real,
	"es_goals_for" integer,
	"es_goals_against" integer,
	"es_goal_difference" integer,
	"es_goals_for_pct" real,
	"es_toi_per_game" real,
	"pp_goals_for" integer,
	"pp_goals_against" integer,
	"pp_toi_per_game" real,
	"sh_goals_for" integer,
	"sh_goals_against" integer,
	"sh_toi_per_game" real,
	"faceoff_win_pct" real,
	"total_faceoffs" integer,
	"offensive_zone_faceoff_pct" real,
	"offensive_zone_faceoffs" integer,
	"defensive_zone_faceoff_pct" real,
	"defensive_zone_faceoffs" integer,
	"neutral_zone_faceoff_pct" real,
	"neutral_zone_faceoffs" integer,
	"ev_faceoff_pct" real,
	"ev_faceoffs" integer,
	"pp_faceoff_pct" real,
	"pp_faceoffs" integer,
	"sh_faceoff_pct" real,
	"sh_faceoffs" integer,
	"pp_goals" integer,
	"pp_assists" integer,
	"pp_points" integer,
	"pp_goals_per_60" real,
	"pp_points_per_60" real,
	"pp_primary_assists" integer,
	"pp_primary_assists_per_60" real,
	"pp_secondary_assists" integer,
	"pp_secondary_assists_per_60" real,
	"pp_shots" integer,
	"pp_shots_per_60" real,
	"pp_shooting_pct" real,
	"pp_individual_sat_for" integer,
	"pp_individual_sat_for_per_60" real,
	"pp_toi" real,
	"pp_toi_pct_per_game" real,
	"sh_goals" integer,
	"sh_assists" integer,
	"sh_points" integer,
	"sh_goals_per_60" real,
	"sh_points_per_60" real,
	"sh_primary_assists" integer,
	"sh_primary_assists_per_60" real,
	"sh_secondary_assists" integer,
	"sh_secondary_assists_per_60" real,
	"sh_shots" integer,
	"sh_shots_per_60" real,
	"sh_shooting_pct" real,
	"sh_individual_sat_for" integer,
	"sh_individual_sat_for_per_60" real,
	"sh_toi" real,
	"sh_toi_pct_per_game" real,
	"pp_goals_against_per_60" real,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nhl_sync_task_config" (
	"task_name" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"interval_live_ms" integer NOT NULL,
	"interval_gameday_ms" integer NOT NULL,
	"interval_quiet_ms" integer NOT NULL,
	"interval_offseason_ms" integer NOT NULL,
	"batch_size" integer,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nhl_goalie_advanced_stats" ADD CONSTRAINT "nhl_goalie_advanced_stats_player_id_nhl_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."nhl_players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nhl_skater_advanced_stats" ADD CONSTRAINT "nhl_skater_advanced_stats_player_id_nhl_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."nhl_players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "nhl_goalie_adv_stats_unique_idx" ON "nhl_goalie_advanced_stats" USING btree ("player_id","season_id","game_type_id");--> statement-breakpoint
CREATE INDEX "nhl_goalie_adv_stats_season_idx" ON "nhl_goalie_advanced_stats" USING btree ("season_id");--> statement-breakpoint
CREATE INDEX "nhl_goalie_adv_stats_player_idx" ON "nhl_goalie_advanced_stats" USING btree ("player_id");--> statement-breakpoint
CREATE UNIQUE INDEX "nhl_skater_adv_stats_unique_idx" ON "nhl_skater_advanced_stats" USING btree ("player_id","season_id","game_type_id");--> statement-breakpoint
CREATE INDEX "nhl_skater_adv_stats_season_idx" ON "nhl_skater_advanced_stats" USING btree ("season_id");--> statement-breakpoint
CREATE INDEX "nhl_skater_adv_stats_player_idx" ON "nhl_skater_advanced_stats" USING btree ("player_id");