#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Provision one logical database + its two roles on an existing PlanetScale
# Postgres cluster. Deployed counterpart to infra/postgres/provision-db.sh.
#
#   ./provision-db.sh <app> [--branch main] [--bws-project <uuid>]
#
# Creates, for <app>:
#   • role  <app>_svc       pg_read_all_data + pg_write_all_data, pg_strict on/on
#   • role  <app>_migrator  same, plus CREATE on the database and schema, warn/warn
#   • logical database <app>, with CONNECT revoked from PUBLIC
#   • two connection URLs, stored in Bitwarden if --bws-project is given
#
# WHY ROLES COME FROM THE API AND NOT SQL: role permissions and query safety are
# platform objects. `ALTER ROLE … SET pg_strict.*` is refused for good (the Default
# role is NOSUPERUSER and lacks ADMIN OPTION on control-plane roles), and raw
# `CREATE ROLE` produces a role the dashboard cannot see or rotate. The create_role
# API is the ONLY path that sets pg_strict without a human in a browser — and it
# only works at creation, since update_role can rename and nothing else. Get it
# right here or fix it by hand later.
#
# WHY `REVOKE CONNECT … FROM PUBLIC` IS THE IMPORTANT LINE: identical to the local
# script's reasoning, and it matters MORE here. Role permissions are cluster-wide,
# so `pg_read_all_data` reads any logical database the role can *connect* to.
# CONNECT is the entire isolation boundary between apps on one cluster.
#
# SECRETS: passwords are generated by PlanetScale and returned exactly once. This
# script never writes them to disk. With --bws-project they go straight to
# Bitwarden; without it they print once to stdout and it is on you to store them.
# A manual copy step is a drift generator (architecture.md §7) — prefer the flag.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

BRANCH=main
BWS_PROJECT=
API=https://api.planetscale.com/v1

die() { echo "error: $*" >&2; exit 1; }
note() { echo "  $*" >&2; }

APP="${1:-}"
[[ -n "$APP" ]] || die "usage: $0 <app> [--branch main] [--bws-project <uuid>]"
shift
while [[ $# -gt 0 ]]; do
  case "$1" in
    --branch)      BRANCH="${2:?}"; shift 2 ;;
    --bws-project) BWS_PROJECT="${2:?}"; shift 2 ;;
    *) die "unknown flag: $1" ;;
  esac
done

# Identifiers are interpolated into SQL, so validation IS the injection defense.
[[ "$APP" =~ ^[a-z][a-z0-9_]{1,30}$ ]] \
  || die "app must match ^[a-z][a-z0-9_]{1,30}\$ (got '$APP')"

for c in psql jq curl; do command -v "$c" >/dev/null || die "missing required tool: $c"; done

: "${PLANETSCALE_SERVICE_TOKEN_ID:?set PLANETSCALE_SERVICE_TOKEN_ID (Settings > Service tokens)}"
: "${PLANETSCALE_SERVICE_TOKEN:?set PLANETSCALE_SERVICE_TOKEN}"
: "${PLANETSCALE_ORG:?set PLANETSCALE_ORG (e.g. eric-james-austin)}"
: "${PLANETSCALE_CLUSTER:?set PLANETSCALE_CLUSTER (the PlanetScale database, e.g. alpina-intelligence)}"
: "${PLANETSCALE_ADMIN_URL:?set PLANETSCALE_ADMIN_URL (Default role connection URL)}"

# Everything about *where* to connect is derived from the admin URL rather than
# passed again: host, port, and — critically — the branch id, which is the suffix
# on the Default role's username. One source of truth, no chance of drift.
ADMIN_USER="$(printf '%s' "$PLANETSCALE_ADMIN_URL" | sed -E 's#^[a-z]+://([^:]+):.*#\1#')"
BRANCH_ID="${ADMIN_USER#*.}"
HOSTPORT="$(printf '%s' "$PLANETSCALE_ADMIN_URL" | sed -E 's#^[a-z]+://[^@]+@([^/?]+).*#\1#')"
[[ "$BRANCH_ID" != "$ADMIN_USER" ]] \
  || die "admin URL username has no .<branch-id> suffix — is it the Default role URL?"
SSL='sslmode=verify-full&sslrootcert=system'

ps_api() { # ps_api <method> <path> [json-body]
  local method="$1" path="$2" body="${3:-}" out code
  out="$(curl -sS -w '\n%{http_code}' -X "$method" "$API$path" \
    -H "Authorization: ${PLANETSCALE_SERVICE_TOKEN_ID}:${PLANETSCALE_SERVICE_TOKEN}" \
    -H 'Content-Type: application/json' \
    ${body:+--data "$body"})"
  code="$(tail -n1 <<<"$out")"
  body="$(sed '$d' <<<"$out")"
  [[ "$code" =~ ^2 ]] || die "PlanetScale API $method $path -> HTTP $code: $(head -c 400 <<<"$body")"
  printf '%s' "$body"
}

# ── 1. roles, with query safety set at creation ─────────────────────────────
# pg_strict per ADR-0005 §3: the runtime role BLOCKS unqualified UPDATE/DELETE;
# the migrator only WARNS, because backfills are legitimately unqualified.
create_role() { # create_role <name> <on|warn|off>
  local name="$1" safety="$2"
  ps_api POST "/organizations/$PLANETSCALE_ORG/databases/$PLANETSCALE_CLUSTER/branches/$BRANCH/roles" \
    "$(jq -nc --arg n "$name" --arg s "$safety" '{
         name: $n,
         inherited_roles: ["pg_read_all_data", "pg_write_all_data"],
         require_where_on_update: $s,
         require_where_on_delete: $s
       }')"
}

note "creating role ${APP}_svc (pg_strict on/on) …"
SVC_JSON="$(create_role "${APP}_svc" on)"
note "creating role ${APP}_migrator (pg_strict warn/warn) …"
MIG_JSON="$(create_role "${APP}_migrator" warn)"

SVC_ID="$(jq -r '.id' <<<"$SVC_JSON")"
MIG_ID="$(jq -r '.id' <<<"$MIG_JSON")"
SVC_PW="$(jq -r '.password' <<<"$SVC_JSON")"
MIG_PW="$(jq -r '.password' <<<"$MIG_JSON")"
for v in SVC_ID MIG_ID SVC_PW MIG_PW; do
  [[ -n "${!v}" && "${!v}" != null ]] || die "create_role response missing $v"
done
note "  ${APP}_svc      -> $SVC_ID"
note "  ${APP}_migrator -> $MIG_ID"

# ── 2. logical database + grants ────────────────────────────────────────────
# GRANT/REVOKE take the BARE role id. The dotted <role-id>.<branch-id> form is a
# routing username for connecting only; using it here yields "role does not exist".
#
# <app>_svc gets exactly ONE grant. Postgres' predefined roles already confer
# USAGE on all schemas, so no schema grants and no ALTER DEFAULT PRIVILEGES are
# needed for tables the migrator creates later.
note "creating database $APP and applying grants …"
psql "$PLANETSCALE_ADMIN_URL" -v ON_ERROR_STOP=1 -q <<SQL
SELECT format('CREATE DATABASE %I', '$APP')
 WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$APP')\gexec

REVOKE CONNECT ON DATABASE "$APP" FROM PUBLIC;
GRANT  CONNECT ON DATABASE "$APP" TO "$SVC_ID";
GRANT  CONNECT ON DATABASE "$APP" TO "$MIG_ID";
GRANT  CREATE  ON DATABASE "$APP" TO "$MIG_ID";
SQL

# Schema grants are per-database and do not apply from a `postgres` session, so
# reconnect into the new database. Swap only the PATH of the admin URL — rebuilding
# it from parts would drop the password and the SSL params.
ADMIN_APP_URL="$(printf '%s' "$PLANETSCALE_ADMIN_URL" | sed -E "s#(^[a-z]+://[^/]+)/[^?]*#\1/$APP#")"
psql "$ADMIN_APP_URL" -v ON_ERROR_STOP=1 -q \
  -c "GRANT CREATE, USAGE ON SCHEMA public TO \"$MIG_ID\";" \
  || die "schema grant failed against database '$APP'"

# ── 3. verify, rather than assume ───────────────────────────────────────────
# The assertion that proves isolation: the runtime role reaches its own database
# and holds no CREATE anywhere.
note "verifying the boundary …"
psql "$PLANETSCALE_ADMIN_URL" -A -t -v ON_ERROR_STOP=1 -c "
SELECT CASE WHEN
      has_database_privilege('$SVC_ID', '$APP', 'CONNECT')
  AND has_database_privilege('$MIG_ID', '$APP', 'CONNECT')
  AND has_database_privilege('$MIG_ID', '$APP', 'CREATE')
  AND NOT has_database_privilege('$SVC_ID', '$APP', 'CREATE')
  AND NOT has_database_privilege('public',  '$APP', 'CONNECT')
  THEN 'ok' ELSE 'FAILED' END;" | grep -qx ok \
  || die "privilege boundary assertion failed for '$APP' — inspect before using it"

SVC_URL="postgresql://${SVC_ID}.${BRANCH_ID}:${SVC_PW}@${HOSTPORT}/${APP}?${SSL}"
MIG_URL="postgresql://${MIG_ID}.${BRANCH_ID}:${MIG_PW}@${HOSTPORT}/${APP}?${SSL}"

# pg_strict is invisible to pg_db_role_setting, so the only real check is to
# connect as the role and read the setting back.
SAFETY="$(psql "$SVC_URL" -A -t -c \
  "SELECT current_setting('pg_strict.require_where_on_update',true)||'/'||
          current_setting('pg_strict.require_where_on_delete',true);" 2>/dev/null || true)"
[[ "$SAFETY" == "On/On" ]] \
  || note "WARNING: ${APP}_svc query safety reads '${SAFETY:-unset}', expected On/On"

# ── 4. hand the credentials somewhere durable ───────────────────────────────
UP="$(printf '%s' "$APP" | tr '[:lower:]' '[:upper:]')"
if [[ -n "$BWS_PROJECT" ]] && command -v bws >/dev/null; then
  note "storing connection URLs in Bitwarden project $BWS_PROJECT …"
  bws secret create "${UP}_SVC_DATABASE_URL"      "$SVC_URL" "$BWS_PROJECT" >/dev/null
  bws secret create "${UP}_MIGRATOR_DATABASE_URL" "$MIG_URL" "$BWS_PROJECT" >/dev/null
  STORED="stored in Bitwarden as ${UP}_SVC_DATABASE_URL / ${UP}_MIGRATOR_DATABASE_URL"
else
  STORED="NOT STORED — copy these now, PlanetScale will not show the passwords again:
  ${UP}_SVC_DATABASE_URL=$SVC_URL
  ${UP}_MIGRATOR_DATABASE_URL=$MIG_URL"
fi

cat <<DONE

✓ provisioned '$APP' on $PLANETSCALE_CLUSTER/$BRANCH

  ${APP}_svc       $SVC_ID   CONNECT only, pg_strict on/on    -> Hyperdrive
  ${APP}_migrator  $MIG_ID   + CREATE on db and schema, warn  -> CI only

$STORED

Next: create the Hyperdrive config from the _svc URL and bind it.

  bunx wrangler hyperdrive create $APP \\
    --connection-string="\$${UP}_SVC_DATABASE_URL" --caching-disabled

Then add the binding to apps/$APP/wrangler.jsonc and run \`wrangler types\`.
DONE
